### ISSUE TITLE
create final report

### ISSUE THREAD

**Issue by saurabhmpawar** [saurabhmpawar/clf-tool#5]
@patilaish

**Comment by hrishikeshmahajan007** [comment]
•The proposed tool will thus facilitate user to get a live report of his
redundant running services and unused volumes on cloud, thereby reducing
the organizational cost towards cloud services.
•The security is one of the important concern in cloud services. This tool
will help monitor and secure the cloud environment by managing and
notifying the user all issues concerning security.

**Comment by hrishikeshmahajan007** [comment]
[Reportppt.pptx](https://github.com/saurabhmpawar/clf-tool/files/1339427/Reportppt.pptx)
